apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "network-security-mlops.fullname" . }}-config
  labels:
    {{- include "network-security-mlops.labels" . | nindent 4 }}
data:
  AWS_DEFAULT_REGION: {{ .Values.env.AWS_DEFAULT_REGION | quote }}
  BUCKET_NAME: {{ .Values.env.BUCKET_NAME | quote }}
  PREDICTION_BUCKET_NAME: {{ .Values.env.PREDICTION_BUCKET_NAME | quote }}
  MLFLOW_TRACKING_URI: {{ .Values.env.MLFLOW_TRACKING_URI | quote }}
