apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: network-security-mlops
  namespace: argocd
spec:
  description: Network Security MLOps Application Project
  sourceRepos:
    - "https://github.com/<YOUR_GITHUB_USERNAME>/network-security-mlops.git"
  destinations:
    - namespace: network-security
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
